### ISSUE TITLE
Requirements missing

### ISSUE THREAD

**Issue by ddeimeke** [oetiker/AcmeFetch#13]
I am using the distribution tarball on CentOS 7 and there are some dependencies not installed via `./configure` and `make`.

You need the headers for OpenSSL (package openssl-devel on CentOS).

And without Module::CoreList (package perl-Module-CoreList) nothing happens at all.

```
Making all in thirdparty
make[1]: Entering directory `/home/dirk/workspace/acmefetch-0.4.0/thirdparty'
  GEN      all-local
gmake[2]: Entering directory `/home/dirk/workspace/acmefetch-0.4.0/thirdparty'
gmake[2]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.
  GEN      touch
! Couldn't find module or a distribution Test::Exception (0.4)
! Installing the dependencies failed: Module 'Test::Exception' is not installed
! Bailing out the installation for Crypt-Format-0.06.
! Couldn't find module or a distribution Test::NoWarnings (0.01)
! Installing the dependencies failed: Module 'Crypt::Format' is not installed, Module 'Test::NoWarnings' is not installed
! Bailing out the installation for Crypt-RSA-Parse-0.041.
! Couldn't find module or a distribution IPC::Cmd
! Installing the dependencies failed: Module 'IPC::Cmd' is not installed
! Bailing out the installation for HTTP-Tiny-0.056.
! Installing the dependencies failed: Installed version (0.033) of HTTP::Tiny is not in range '0.054', Module 'Crypt::RSA::Parse' is not installed, Module 'Crypt::Format' is not installed
! Bailing out the installation for Protocol-ACME-0.11.
Data::Processor is up to date. (0.4.2)
Pod::Usage is up to date. (1.68)
JSON is up to date. (2.90)
Crypt::OpenSSL::X509 is up to date. (1.806)
Net::SSLeay is up to date. (1.72)
IO::Socket::SSL is up to date. (2.024)
gmake[2]: *** [touch] Error 123
gmake[2]: Leaving directory `/home/dirk/workspace/acmefetch-0.4.0/thirdparty'
make[1]: *** [all-local] Error 2
make[1]: Leaving directory `/home/dirk/workspace/acmefetch-0.4.0/thirdparty'
make: *** [all-recursive] Error 1
```

**Comment by oetiker** [comment]
Does this mean on centos7 you get a copy of perl which is missing the core modules ?

what happens when you do a

`make distclean`

and then `./bootstrap`

**Comment by oetiker** [comment]
so I guess configure should check if it is running on centos and verify that the appropriate packages are installed ... do you have some rpm shell commands I could execute to verify this ? also how do I detect that I am on centos (sorry for the questions ... but its so much easier than venturing out into redhat land :))

**Comment by ddeimeke** [comment]
The minimal installation of RedHat/CentOS 7 does not even has Perl installed (Python instead).

`./bootstrap` gives an error:
line2: autoreconf: command not found.

So I added automake and autoconf as well.

Result: "no config.status cannot remake."

Check: `rpm -qa | grep perl-Module-CoreList`

Checking the OS: https://github.com/ddeimeke/littlehelpers/blob/master/bash/os.bash

Just keep asking, I try my best to answer.

**Comment by ddeimeke** [comment]
BTW: If needed, I can quickly provide a minimal CentOS VM via DigitalOcean. (Just send me your SSH Public Key).

**Comment by oetiker** [comment]
ok lets do that ...

**Comment by oetiker** [comment]
try version 0.4.1
