### ISSUE TITLE
unzip

### ISSUE THREAD

**Issue by ddeimeke** [oetiker/AcmeFetch#15]
unzip is needed as well to build AcmeFetch (currently building with a minimal installation and writing a blog article).

**Comment by oetiker** [comment]
any idea WHO needs this ? do you have an error message to share ?

**Comment by ddeimeke** [comment]
The module build process (cpan) gave the error message that unzip was not installed.

Maybe update the readme and add unzip to "apt-get install" and "yum install". (That's all).

**Comment by oetiker** [comment]
99fa24c should take care of this it is in release 0.4.2
