### ISSUE TITLE
failure on OmniOS r1510402+ when openssl mediator is set to 3

### ISSUE THREAD

**Issue by cmchittom** [oetiker/AcmeFetch#34]
OmniOS [r151042](https://github.com/omniosorg/omnios-build/blob/r151042/doc/ReleaseNotes.md#r151042a-2022-05-04) changed the default openssl mediator to 3.  When running in a zone with it set to 3, acmefetch seems to error out with
```
Config ERROR: root->GENERAL: Execution of validator for 'opensslBin' returns with error: Openssl openssl not found
```
and a certificate is not created.

After setting the openssl mediator back to 1.1, acmefetch works without issue.

**Comment by oetiker** [comment]
yes, acmefetch does not yet work with openssl 3 ... PR welcome

the config check explicitly tests if openssl 1 is present ...

**Comment by hadfl** [comment]
no need to change the mediator, you could as well use `opensslBin` in the config to point to the openssl 1.1 binary. however this should still be fixed to work with openssl 3
