### ISSUE TITLE
Ubuntu 22.04: Execution of validator for 'opensslBin' returns with error: Openssl openssl not found

### ISSUE THREAD

**Issue by ddeimeke** [oetiker/AcmeFetch#39]
Hi!

I updated one of my systems to Ubuntu 22.04, and I get the following error when trying to run acmefetch:

```
Config ERROR: root->GENERAL: Execution of validator for 'opensslBin' returns with error: Openssl openssl not found
Can't continue with config errors
```

Any ideas?

Dirk

**Comment by oetiker** [comment]
acmefetch checks the version of openssl by running `openssl version` and in the current acmefetch version the response should match `/OpenSSL [13]/ `

maybe you are running an old copy of acmefetch ?

**Comment by ddeimeke** [comment]
Hmpf, too easy, Tobi.

Everything works well after an update.

Sorry for the noise!
